# This Ansible playbook installs a no-subscription (free) version of Proxmox VE 7 on Debian 11 Bullseye
# The reference documentation is:
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye
---
- name: Install Proxmox VE with dynamic hostname & public IP
  hosts: all
  become: true

  tasks:
    - name: Set hostname fact
      command: hostname
      register: hostname_output

    - name: Fetch remote public IP from ident.me
      uri:
        url: https://ident.me
        return_content: yes
      register: public_ip

    - name: Set public IP fact
      set_fact:
        ip_address: "{{ public_ip.content }}"

    - name: Display gathered information
      debug:
        msg: "Hostname: {{ hostname_output.stdout }}, Public IP: {{ ip_address }}"

    - name: Configure /etc/hosts file (inline version)
      copy:
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        content: |
          127.0.0.1   localhost
          {{ ip_address }}   {{ hostname_output.stdout }} {{ hostname_output.stdout }}

          # The following lines are desirable for IPv6 capable hosts
          ::1     localhost ip6-localhost ip6-loopback
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters
    - name: Add Proxmox VE repository to sources list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/pve-install-repo.list
        content: 'deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
        owner: root
        group: root
        mode: '0644'
    - name: Download Proxmox GPG key to trusted.gpg.d
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
        mode: '0644'
        owner: root
        group: root
    - name: Update apt cache and perform full upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
    - name: Install Proxmox kernel 5.15
      ansible.builtin.apt:
        name: pve-kernel-5.15
        state: present
        update_cache: yes

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: whoami

    - name: Remove Proxmox enterprise repository file if it exists
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
    - name: Install Proxmox VE, Postfix, and Open-iSCSI
      ansible.builtin.apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
        state: present
        update_cache: yes
    - name: Remove linux-image-amd64 and all linux-image-5.10* packages
      apt:
        name:
          - linux-image-amd64
          - 'linux-image-5.10*'
        state: absent
        purge: yes
        autoremove: yes
        force: yes
      become: true
    - name: Update GRUB configuration
      ansible.builtin.command: update-grub
      become: true
    - name: Remove os-prober package
      ansible.builtin.apt:
        name: os-prober
        state: absent
      become: true
